import Herobanner1 from "../src/assets/images/BannerHeros1.jpg";
import HoChiMinh from "./assets/images/Hochiminh.jpg";

const sampleToursData = [
  {
    id: "1",
    image:
      "https://images.unsplash.com/photo-1571409949673-98319e712959?q=80&w=2070&auto=format&fit=crop",
    tags: ["Đắt ngay hôm nay", "Miễn phí hủy"],
    title: "Vé Xe Buýt 2 Tầng Ngắm Cảnh ở Thành Phố Hồ Chí Minh",
    rating: 4.6,
    reviewsCount: 3281,
    bookingsCount: "100k+",
    price: "111.000",
    currency: "VNĐ",
    salePercentage: "20%",
  },
  {
    id: "2",
    image:
      "https://images.unsplash.com/photo-1563290886-2200a897f98b?q=80&w=1974&auto=format&fit=crop",
    tags: ["Ưu đãi độc quyền"],
    title: "Du thuyền ăn tối Sài Gòn và xem Show múa",
    rating: 4.8,
    reviewsCount: 1240,
    bookingsCount: "50k+",
    price: "950.000",
    currency: "VNĐ",
    salePercentage: "15%",
  },
  {
    id: "3",
    image:
      "https://images.unsplash.com/photo-1596422849503-d1e571c61b2a?q=80&w=1964&auto=format&fit=crop",
    tags: ["Bán chạy"],
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    rating: 4.7,
    reviewsCount: 5820,
    bookingsCount: "200k+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id: "4",
    image:
      "https://images.unsplash.com/photo-1596422849503-d1e571c61b2a?q=80&w=1964&auto=format&fit=crop",
    tags: ["Bán chạy"],
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    rating: 4.7,
    reviewsCount: 5820,
    bookingsCount: "200k+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id: "5",
    image:
      "https://images.unsplash.com/photo-1596422849503-d1e571c61b2a?q=80&w=1964&auto=format&fit=crop",
    tags: ["Bán chạy"],
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    rating: 4.7,
    reviewsCount: 5820,
    bookingsCount: "200k+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
];

export { sampleToursData };
export const heroBannersData = [
  {
    id: 1,
    imageUrl: Herobanner1, // Sử dụng ảnh trong /public/images/
    title: "KHÁM PHÁ CÁC ĐỊA ĐIỂM DU LỊCH NỔI TIẾNG",
    description:
      "Mở ra chân trời mới, đam mê mới và danh sách phiêu lưu bất tận của bạn cùng Klook - trên mọi hành trình, dù gần hay xa.",
    buttonText: "Khám phá ngay",
  },
  {
    id: 2,
    imageUrl: "./assets/images/BannerHero_2.jfif",
    title: "TRẢI NGHIỆM HÀNG ĐẦU CHÂU Á",
    description:
      "Từ những bãi biển nhiệt đới đến các thành phố sôi động, luôn có một hành trình đang chờ đợi bạn.",
    buttonText: "Xem các tour",
  },
  {
    id: 3,
    imageUrl: "./assets/images/BannerHero_3.jfif",
    title: "ƯU ĐÃI ĐỘC QUYỀN MÙA HÈ",
    description:
      "Giảm giá lên đến 30% cho các hoạt động và vé tham quan. Đừng bỏ lỡ!",
    buttonText: "Săn ưu đãi",
  },
];
// /frontend/src/data.js

// ... (thêm vào cuối file)
export const experienceData = [
  {
    id: "e1",
    image: "/images/exp-venice.jpg", // Thay bằng ảnh của bạn trong /public/images/
    title: "Chốt gấp kèo TPHCM",
    subtitle1: "Deal du lịch hot nhất",
    subtitle2: "Du lịch TPHCM",
    buttonText: "khám phá",
  },
  {
    id: "e2",
    image: "/images/exp-venice.jpg",
    title: "Chốt gấp kèo TPHCM",
    subtitle1: "Deal du lịch hot nhất",
    subtitle2: "Du lịch TPHCM",
    buttonText: "khám phá",
  },
  {
    id: "e3",
    image: "/images/exp-venice.jpg",
    title: "Chốt gấp kèo TPHCM",
    subtitle1: "Deal du lịch hot nhất",
    subtitle2: "Du lịch TPHCM",
    buttonText: "khám phá",
  },
  {
    id: "e4",
    image: "/images/exp-venice.jpg",
    title: "Chốt gấp kèo TPHCM",
    subtitle1: "Deal du lịch hot nhất",
    subtitle2: "Du lịch TPHCM",
    buttonText: "khám phá",
  },
];

export const chotkeoData =[
  {
    id:"c1",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c2",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c3",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c4",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c5",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c6",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c7",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c8",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
  {
    id:"c9",
    image: HoChiMinh,
    title: "Tour Nửa Ngày Địa Đạo Củ Chi từ TP. Hồ Chí Minh",
    tags: ["Xác nhận tức thời"],
    rating: 4.8,
    reviewsCount: 105314,
    bookingsCount: "4M+",
    price: "685.000",
    currency: "VNĐ",
    salePercentage: "10%",
  },
];